//! Runtime for parsers generated by the ultra-parser tool.
//!
//! The tool's `Rust` target emits a [`GrammarData`] per recognizer: the serialized ATN of the grammar
//! and its names. [`LexerInterpreter`] and [`ParserInterpreter`] interpret that ATN like ANTLR's
//! interpreters do, including adaptive LL(*) prediction and ANTLR's default error recovery.
//! Actions and semantic predicates in grammars are not run; predicates always succeed.

mod atn;
mod config;
mod context;
mod interval_set;
mod lexer;
mod ll1;
mod parser;
mod prediction;
mod semantic;
mod token;
mod tree;

use std::fmt;

pub use atn::AtnError;
pub use interval_set::IntervalSet;
pub use token::{DEFAULT_CHANNEL, EOF, HIDDEN_CHANNEL, Token, Vocabulary};
pub use tree::{Child, NodeId, ParseTree, RuleNode};

use atn::{Atn, GrammarType};

/// The data the tool generates for a lexer or parser.
#[derive(Clone, Copy, Debug)]
pub struct GrammarData {
    pub grammar_file_name: &'static str,
    pub recognizer_name: &'static str,
    pub serialized_atn: &'static [i32],
    pub rule_names: &'static [&'static str],
    pub literal_names: &'static [Option<&'static str>],
    pub symbolic_names: &'static [Option<&'static str>],
    /// Channel names of a lexer; empty for parsers.
    pub channel_names: &'static [&'static str],
    /// Mode names of a lexer; empty for parsers.
    pub mode_names: &'static [&'static str],
}

impl GrammarData {
    pub fn vocabulary(&self) -> Vocabulary {
        Vocabulary {
            literal_names: self.literal_names,
            symbolic_names: self.symbolic_names,
        }
    }

    fn deserialize(&self, expected: GrammarType) -> Result<Atn, AtnError> {
        let atn = Atn::deserialize(self.serialized_atn)?;
        if atn.grammar_type != expected {
            return Err(AtnError::wrong_grammar_type(self.recognizer_name));
        }
        Ok(atn)
    }
}

/// A syntax error, located at a token or at the text the lexer could not match.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SyntaxError {
    /// 1-based line.
    pub line: usize,
    /// 0-based column in code points.
    pub column: usize,
    /// Offset of the first code point.
    pub start: usize,
    /// Offset just past the last code point.
    pub end: usize,
    pub message: String,
}

impl fmt::Display for SyntaxError {
    /// Formats the error like ANTLR's `ConsoleErrorListener`, e.g., `line 1:4 missing ')' at '<EOF>'`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "line {}:{} {}", self.line, self.column, self.message)
    }
}

pub struct LexerInterpreter {
    data: &'static GrammarData,
    atn: Atn,
}

impl LexerInterpreter {
    pub fn new(data: &'static GrammarData) -> Result<Self, AtnError> {
        Ok(Self {
            data,
            atn: data.deserialize(GrammarType::Lexer)?,
        })
    }

    pub fn data(&self) -> &'static GrammarData {
        self.data
    }

    /// Splits `source` into tokens, ending with an EOF token. Tokens skipped by the grammar are
    /// dropped; tokens on other channels are kept.
    pub fn tokenize(&self, source: &str) -> (Vec<Token>, Vec<SyntaxError>) {
        lexer::Lexer::new(&self.atn, source).tokenize()
    }
}

pub struct ParserInterpreter {
    data: &'static GrammarData,
    atn: Atn,
}

/// The result of parsing: a tree is produced even for invalid input, thanks to error recovery.
#[derive(Clone, Debug)]
pub struct ParseOutput {
    pub tree: ParseTree,
    pub errors: Vec<SyntaxError>,
}

impl ParserInterpreter {
    pub fn new(data: &'static GrammarData) -> Result<Self, AtnError> {
        Ok(Self {
            data,
            atn: data.deserialize(GrammarType::Parser)?,
        })
    }

    pub fn data(&self) -> &'static GrammarData {
        self.data
    }

    /// Parses `tokens`, which must end with an EOF token, starting from rule `start_rule`.
    pub fn parse(&self, tokens: &[Token], start_rule: usize) -> ParseOutput {
        assert!(
            tokens.last().is_some_and(|t| t.token_type == EOF),
            "tokens must end with an EOF token"
        );
        assert!(
            start_rule < self.data.rule_names.len(),
            "invalid start rule {start_rule}"
        );
        let parser = parser::Parser::new(
            &self.atn,
            self.data.vocabulary(),
            self.data.rule_names,
            tokens,
        );
        let (tree, errors) = parser.parse(start_rule);
        ParseOutput { tree, errors }
    }
}
